### PR TITLE
Use Url.Action instead of a hardcoded URI

### PR DESCRIPTION
**Pull request by dpodder**
`Url.Action(...)` is a built-in MVC helper function that can build up a URI regardless of where the website is running. This allows the code to work regardless of where the webpage is deployed (`localhost`, `jdash-et`, `jdash`, etc).

### CODE REVIEW

**Comment by dpodder** [comment]
@smile21prc PTAL

**Comment by smile21prc** [comment]
I like this API. However, I got multiple build errors with this change (will Email you the screenshot). Is this change complete? Or some dependent changes are also necessary?

**Comment by smile21prc** [comment]
Just retried with clean build after rebase to Origin/Master, it's clean now. LGTM

**Comment by dpodder** [comment]
Resolved offline, builds clean now

**Pull request merged**
